services:
  bluetooth-service:
    image: bluez-image
    privileged: true
    networks:
      - bluetooth-network
  nginx_aiohttp_service:
    build: ./buzzer
    restart: unless-stopped
    networks:
      - bluetooth-network
    devices:
      - "/dev/bus/usb"
    volumes:
      - ~/buzzer:/buzzerlog    
    expose:
      - 5000
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 1338:1338
    depends_on:
      - nginx_aiohttp_service

networks:
  bluetooth-network:
    driver: bridge
