upstream nginxaiohttpexample {
    server nginx-aiohttp-service:5000;
}

server {

    listen 1338;

    location / {
        proxy_pass http://nginxaiohttpexample;
        proxy_set_header Host  $host;
        proxy_set_header X-User  $user;
        proxy_set_header X-Access-Token $token;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
