upstream nginxaiohttpexample {
    server nginx-aiohttp-service:5000;
}

server {

    listen 1338;

    location / {
        proxy_pass http://nginxaiohttpexample/;
        proxy_redirect     off;
    }
}
